-- AlterTable
ALTER TABLE "Order" ALTER COLUMN "name" SET DEFAULT '';
ALTER TABLE "Order" ALTER COLUMN "email" SET DEFAULT '';
ALTER TABLE "Order" ALTER COLUMN "address" SET DEFAULT '';
ALTER TABLE "Order" ALTER COLUMN "zipCode" SET DEFAULT '';
ALTER TABLE "Order" ALTER COLUMN "city" SET DEFAULT '';
ALTER TABLE "Order" ALTER COLUMN "country" SET DEFAULT '';
ALTER TABLE "Order" ALTER COLUMN "products" SET DEFAULT '[]';
ALTER TABLE "Order" ALTER COLUMN "price" SET DEFAULT 0;
ALTER TABLE "Order" ALTER COLUMN "date" SET DEFAULT 0;
ALTER TABLE "Order" ALTER COLUMN "month" SET DEFAULT 0;
ALTER TABLE "Order" ALTER COLUMN "year" SET DEFAULT 0;
ALTER TABLE "Order" ALTER COLUMN "delivaryCharge" SET DEFAULT 0;
