-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "date" STRING NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN     "month" STRING NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN     "year" STRING NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "date" STRING NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN     "month" STRING NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN     "year" STRING NOT NULL DEFAULT '';
